name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: generate-snake-game-from-github-contribution-grid
      uses: Platane/snk@v3.2.0
      with:
        github_user_name: yeonsooooooo
        svg_out_path: dist/github-snake.svg
